//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notifications.BalloonMessage.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notifications.BalloonMessage.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a windows balloon tip message. .
        /// </summary>
        internal static string BalloonMessageDescription {
            get {
                return ResourceManager.GetString("BalloonMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balloon Message.
        /// </summary>
        internal static string BalloonMessageDisplayName {
            get {
                return ResourceManager.GetString("BalloonMessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in milliseconds the balloon message should stay on the screen. .
        /// </summary>
        internal static string BalloonMessageDisplayTimeoutDescription {
            get {
                return ResourceManager.GetString("BalloonMessageDisplayTimeoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string BalloonMessageDisplayTimeoutDisplayName {
            get {
                return ResourceManager.GetString("BalloonMessageDisplayTimeoutDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTipIcon.Info, ToolTipIcon.Error, or ToolTipIcon.Warning,.
        /// </summary>
        internal static string BalloonMessageIconTypeDescription {
            get {
                return ResourceManager.GetString("BalloonMessageIconTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Type.
        /// </summary>
        internal static string BalloonMessageIconTypeDisplayName {
            get {
                return ResourceManager.GetString("BalloonMessageIconTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text message you would like displayed on the balloon message. .
        /// </summary>
        internal static string BalloonMessageMessageDescription {
            get {
                return ResourceManager.GetString("BalloonMessageMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balloon Message.
        /// </summary>
        internal static string BalloonMessageMessageDisplayName {
            get {
                return ResourceManager.GetString("BalloonMessageMessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean Value. True the Balloon Message is sent so it can be shown..
        /// </summary>
        internal static string BalloonMessageShowBalloonMessageDescription {
            get {
                return ResourceManager.GetString("BalloonMessageShowBalloonMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Balloon Message.
        /// </summary>
        internal static string BalloonMessageShowBaloonMessageDisplayName {
            get {
                return ResourceManager.GetString("BalloonMessageShowBaloonMessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title of the balloon tip message..
        /// </summary>
        internal static string BalloonMessageTitleDescription {
            get {
                return ResourceManager.GetString("BalloonMessageTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string BalloonMessageTitleDisplayName {
            get {
                return ResourceManager.GetString("BalloonMessageTitleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        internal static string MetadataValidationError {
            get {
                return ResourceManager.GetString("MetadataValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Scope.
        /// </summary>
        internal static string ParentScope {
            get {
                return ResourceManager.GetString("ParentScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains and authenticates all child activities..
        /// </summary>
        internal static string ParentScopeDescription {
            get {
                return ResourceManager.GetString("ParentScopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity is only valid inside a Parent Scope..
        /// </summary>
        internal static string ValidationMessage {
            get {
                return ResourceManager.GetString("ValidationMessage", resourceCulture);
            }
        }
    }
}
